# Generated by Django 4.0 on 2021-12-16 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0002_alter_category_options_book_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('books', models.ManyToManyField(to='main.Book')),
                ('products', models.ManyToManyField(to='main.Product')),
            ],
            options={
                'ordering': ['cart_id', '-create_at'],
            },
        ),
    ]
